# to run multiple service or app (independently) at a time we have to use api gateway or different ports numbers
server:
  port: 6003
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transactiondb?createDatabaseIfNotExist=true
    username: root
    password: king
  jpa:
    hibernate.ddl-auto: create
    show-sql: true